version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    environment:
      STRAPI_PREVIEW_SECRET:
      NEXT_PUBLIC_STRAPI_API_URL:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
  generator:
    build:
      context: src/generator/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do dotnet generator.dll /usr/src/data/config.json /usr/src/data/tiles.json; sleep 12h & wait $${!}; done;'"
  proxy:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend
      - backend
  # https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  certbot:
    image: certbot/dns-digitalocean
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
