version: '3.3'

services:
  frontend:
    image: rikkit/homepage_frontend
    command: yarn start
    volumes:
      - /root/homepage/data/frontend/build:/usr/src/frontend/.next
  backend:
    image: rikkit/homepage_backend
    command: yarn start
    volumes:
      - /root/homepage/data/backend/data.db:/usr/src/backend/.tmp/data.db
    ports:
      - "1337:1337"
  generator:
    image: rikkit/homepage_generator
    volumes:
      - /root/homepage/data/tiles/:/usr/src/data/
  proxy:
    image: rikkit/homepage_proxy
    volumes:
      - ./src/proxy/nginx.host.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/tiles/tiles.json:/var/www/data/tiles.json
  certbot:
    volumes:
      - ./data/.digitalocean.ini:/root/.digitalocean.ini
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot