//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace generator.Tiles {
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Templates() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("generator.Templates", typeof(Templates).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;{{title}}&lt;/title&gt;
        ///
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;{{webroot}}/app.css&quot;/&gt;
        ///    &lt;link href=&quot;http://fonts.googleapis.com/css?family=Open+Sans:300,400,700&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;{{webroot}}/js/vendor.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;{{webroot}}/js/app.js&quot;&gt;&lt;/script&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string skeleton {
            get {
                return ResourceManager.GetString("skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;div class=&quot;tile {{Size}} {{Style}}&quot;&gt;
        ///    &lt;a class=&quot;tile-link&quot; href=&quot;{{Link}}&quot;&gt; &lt;/a&gt;
        ///    &lt;div class=&quot;faces&quot;&gt;
        ///        &lt;div class=&quot;front&quot;&gt; &lt;/div&gt;
        ///        &lt;div class=&quot;back&quot;&gt;
        ///            &lt;ul class=&quot;tile-content&quot;&gt;
        ///                {{#each Content}}
        ///                &lt;li class=&quot;fill-template template-image {{#if Overlay}}overlay{{/if}}&quot; style=&quot;background-image: url(&amp;quot;{{Image}}&amp;quot;)&quot;&gt;
        ///                    &lt;h3 class=&quot;template-lead&quot;&gt;{{Name}}&lt;/h3&gt;
        ///                    &lt;p class=&quot;template-body&quot;&gt;{{Body}}&lt;/p&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tt_01 {
            get {
                return ResourceManager.GetString("tt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;div class=&quot;tile {{Size}} {{Style}}&quot;&gt;
        ///    &lt;a class=&quot;tile-link&quot; href=&quot;{{Link}}&quot;&gt; &lt;/a&gt;
        ///    &lt;p class=&quot;title&quot;&gt;{{Title}}&lt;/p&gt;
        ///    &lt;div class=&quot;template-overlay&quot;&gt;&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string tt_02 {
            get {
                return ResourceManager.GetString("tt_02", resourceCulture);
            }
        }
    }
}
