//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage.Generator.Tiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("homepage.Generator.Tiles.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{{title}}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Rikki Tooley&lt;/h1&gt;
        ///&lt;article class=&quot;content&quot;&gt;
        ///    {{content}}
        ///&lt;/article&gt;
        ///&lt;div class=&quot;tiles&quot;&gt;
        ///    {{tiles}}
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string skeleton {
            get {
                return ResourceManager.GetString("skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;tile {{Size}} {{Style}}&quot;&gt;
        ///    &lt;a class=&quot;tile-link&quot; href=&quot;{{Link}}&quot;&gt; &lt;/a&gt;
        ///    &lt;div class=&quot;faces&quot;&gt;
        ///        &lt;div class=&quot;front&quot;&gt; &lt;/div&gt;
        ///        &lt;div class=&quot;back&quot;&gt;
        ///            &lt;ul class=&quot;tile-content&quot;&gt;
        ///                {{#each Content}}
        ///                &lt;li class=&quot;fill-template template-image&quot; style=&quot;background-image: url(&amp;quot;{{Image}}&amp;quot;)&quot;&gt;
        ///                    &lt;h3 class=&quot;template-lead&quot;&gt;{{Name}}&lt;/h3&gt;
        ///                    {{#if Overlay}}
        ///                    &lt;div class=&quot;template-overlay&quot;&gt;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tt_01 {
            get {
                return ResourceManager.GetString("tt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;tile {{Size}} {{Style}}&quot;&gt;
        ///    &lt;a class=&quot;tile-link&quot; href=&quot;{{Link}}&quot;&gt; &lt;/a&gt;
        ///    &lt;p class=&quot;title&quot;&gt;{{Title}}&lt;/p&gt;
        ///    &lt;div class=&quot;template-overlay&quot;&gt;&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string tt_02 {
            get {
                return ResourceManager.GetString("tt_02", resourceCulture);
            }
        }
    }
}
